services:
  - type: web
    plan: free
    name: djangoweather
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn djangoweather.asgi:application -k uvicorn.workers.UvicornWorker"
